server:
  port: 8090
druid:
  allow:
    ip: 127.0.0.1
  login:
    user_name: root
    password: root

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cunple?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-idle: 5
    max-wait-millis: 60000
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# dubbo config
# 应⽤用定义了了提供⽅方应⽤用信息，⽤用于计算依赖关系；在 dubbo-admin 或 dubbo-monitor 会显示这个
dubbo:
  application:
    name: user-app

  # 使⽤用 zookeeper 注册中⼼心暴暴露露服务，注意要先开启 zookeeper
  # 注册中⼼心id
  registry:
    id: zookeeper-registry
    # 注册中⼼心协议
    protocol: zookeeper
    # 注册中⼼心地址
    address: 119.23.219.183:2181
    # dubbo协议在20880端⼝口暴暴露露服务
    # 协议名称
  protocol:
    name: dubbo
    # 协议端⼝口
    port: 20880
    # 协议访问log
    accesslog: dubbo-access.log
    # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000
    # 注册监控中⼼心
  monitor:
    protocol: registry